"""refactor_role_system_tables

Revision ID: 9a7c4bd7f774
Revises: 4a4012e49a91
Create Date: 2026-04-29 10:08:20.888399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '9a7c4bd7f774'
down_revision: Union[str, Sequence[str], None] = '4a4012e49a91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('taskassignment_jury_member_id_fkey', 'taskassignment', type_='foreignkey')
    op.drop_constraint('userrole_role_id_fkey', 'userrole', type_='foreignkey')
    op.drop_column('taskassignment', 'jury_member_id')
    op.drop_column('userrole', 'role_id')
    op.drop_table('role')
    op.drop_table('jurymember')
    role_enum = sa.Enum('ADMIN', 'JURY', 'PARTICIPANT', name='roleenum')
    role_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('userrole', sa.Column('role', role_enum, nullable=False))
    op.add_column('taskassignment', sa.Column('evaluator_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'taskassignment', 'userrole', ['evaluator_id'], ['id'], ondelete='CASCADE')
    op.add_column('evaluation', sa.Column('requirement_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'evaluation', 'requirement', ['requirement_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'evaluation', type_='foreignkey')
    op.drop_column('evaluation', 'requirement_id')
    op.drop_constraint(None, 'taskassignment', type_='foreignkey')
    op.drop_column('taskassignment', 'evaluator_id')
    op.drop_column('userrole', 'role')
    sa.Enum(name='roleenum').drop(op.get_bind(), checkfirst=True)
    op.create_table('role',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('name', sa.String(), nullable=False)
    )
    op.create_table('jurymember',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('user_id', sa.Integer(), sa.ForeignKey('user.id', ondelete='CASCADE')),
        sa.Column('tournament_id', sa.Integer(), sa.ForeignKey('tournament.id', ondelete='CASCADE'))
    )
    op.add_column('userrole', sa.Column('role_id', sa.Integer(), nullable=True))
    op.create_foreign_key('userrole_role_id_fkey', 'userrole', 'role', ['role_id'], ['id'], ondelete='CASCADE')
    op.add_column('taskassignment', sa.Column('jury_member_id', sa.Integer(), nullable=True))
    op.create_foreign_key('taskassignment_jury_member_id_fkey', 'taskassignment', 'jurymember', ['jury_member_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
