"""Fix TaskAssignment table

Revision ID: 9f94110a9cec
Revises: 1f6b3a8ea470
Create Date: 2026-05-13 14:30:53.608532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f94110a9cec'
down_revision: Union[str, Sequence[str], None] = '1f6b3a8ea470'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('taskassignment_evaluator_id_fkey'), 'taskassignment', type_='foreignkey')
    op.create_foreign_key(None, 'taskassignment', 'user', ['evaluator_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'taskassignment', type_='foreignkey')
    op.create_foreign_key(op.f('taskassignment_evaluator_id_fkey'), 'taskassignment', 'userrole', ['evaluator_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
