"""fix_user_and_submission_schema

Revision ID: e4df1dde5ce2
Revises: 07bedd5ca031
Create Date: 2026-04-06 17:08:14.707156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e4df1dde5ce2'
down_revision: Union[str, Sequence[str], None] = '07bedd5ca031'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission', sa.Column('github_url', sa.String(), nullable=False))
    op.add_column('submission', sa.Column('video_url', sa.String(), nullable=False))
    op.add_column('submission', sa.Column('live_demo_url', sa.String(), nullable=True))
    op.add_column('submission', sa.Column('description', sa.String(), nullable=True))
    op.alter_column('user', 'password',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('submission', 'description')
    op.drop_column('submission', 'live_demo_url')
    op.drop_column('submission', 'video_url')
    op.drop_column('submission', 'github_url')
    # ### end Alembic commands ###
